WINDOW_TITLE = "Pomodoro App"
WINDOW_HEIGHT = 400
WINDOW_WIDTH = 380

START_BUTTON_TEXT = "Start"
RESET_BUTTON_TEXT = "Reset"

CHECK_MARK = "✓"

PINK = "#e2979c"
RED = "#e7385b"
GREEN = "#9bdeac"
YELLOW = "#f7f5dd"
FONT_NAME = "Courier"
FONT_SIZE = 20
WORK_MIN = 25
SHORT_BREAK_MIN = 5
LONG_BREAK_MIN = 20

SHORT_BREAK = SHORT_BREAK_MIN * 60
LONG_BREAK = LONG_BREAK_MIN * 60
WORK_TIME = WORK_MIN * 60